### ISSUE TITLE
library package uber jar by dafault without maven shade, so conflict with aerospike-client

### ISSUE THREAD

**Issue by kuzkdmy** [aerospike/aerospike-helper#19]
Library is packaged as uber jar by dafault without maven shade, so there is conflict when include aerospike-client as dependency
Generally there should be two artifacts:
- regular one
- uber jar with shaded dependencies
Thanks.

**Comment by mzhangsfly** [comment]
This library has been moved to QueryEngine as one of java client extensions, try to have a look at:
https://github.com/aerospike/aerospike-client-java/tree/master/extensions/query-engine

Thanks,

**Comment by kuzkdmy** [comment]
I have found this. I removed aerospike-client from my dependencies to make it works.
Not sure that there is a need to change something in project build.
Thanks.
