### ISSUE TITLE
Release ?

### ISSUE THREAD

**Issue by harksin** [aerospike/aerospike-helper#8]
Aerospike-spark driver depend on the query engine present in this package.
Do you plan to continue to maintain, release and publish this repo ?

Does query engine exist anywhere else ?

**Comment by jboone100** [comment]
Current release of the aerospike-helper for java which is used by the Aerospike-spark driver is [1.2.1](https://search.maven.org/#artifactdetails%7Ccom.aerospike%7Caerospike-helper-java%7C1.2.1%7Cjar). We will continue to maintain and publish new releases of this jar as new features become available in the java client and/or server. The query engine is also used by the Spring Data Aerospike project.
